name: mytuition
description: "Final Year Project 2025 UTM"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8

  # Routing
  go_router: ^14.8.1

  # State Management
  bloc: ^9.0.0
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7

  # Firebase
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  firebase_storage: ^12.4.4

  # Dependency Injection
  get_it: ^8.0.3

  # Local Storage
  shared_preferences: ^2.5.2

  # Network
  http: ^1.3.0

  # Utils
  intl: ^0.20.2
  uuid: ^4.5.1
  path_provider: ^2.1.5

  # API Integration
  dio: ^5.8.0+1

  # QR Code and NFC
  qr_flutter: ^4.1.0
  mobile_scanner: ^6.0.7

  # Other
  flutter_svg: ^2.0.17
  cached_network_image: ^3.4.1
  connectivity_plus: ^5.0.2
  image_picker: ^1.1.2
  flutter_launcher_icons: ^0.14.3
  wolt_modal_sheet: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  bloc_test: ^10.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.8

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
